name: Create GitHub Releases based on changelog
description: GitHub Action for creating GitHub Releases based on changelog

inputs:
  changelog:
    description: Path to changelog
    required: false
  title:
    description: Format of title (variables `$tag`, `$version`, and any string)
    required: false
    default: '$tag'
  draft:
    description: Create a draft release ('true' or 'false')
    required: false
    default: 'false'
  branch:
    description: Reject releases from commits not contained in branches that match the specified pattern (regular expression)
    required: false
  prefix:
    description: >
      A prefix for the release tag, before the version number (for
      example, 'my-crate-v0.1.2' has the prefix 'my-crate-').

      The prefix may not contain regular expression characters such as `\`, `.`,
      `(`, `)`, `[`, `]`, `{` and `}`.
    required: false
    default: ''

runs:
  using: node12
  main: main.js
